### ISSUE TITLE
How to set custom Icon in place of Tick Mark

### ISSUE THREAD

**Issue by jyotisolanki** [cortinico/slidetoact#14]
Hello how would I change tick circle into my custom icon

**Comment by cortinico** [comment]
Can you please provide a bit more context?
What do you mean with `tick circle` ?

**Comment by jyotisolanki** [comment]
Hello
As in your library after sliding it shows an image of Tick mark icon so in place of this i want to put my image . how can i do this?

**Comment by rsansores** [comment]
Hi, 

@cortinico First of all, great work, your widget is really well made.

I'm trying to achieve the exact same thing as @jyotisolanki. Right now what I did is checkout the project and make public the animated_check_icon. But I think it could be a great addition to your component instead of forking it.

Here is what I'm trying to achieve.

1. The user slides the component.
2. If the slide was complete then I call a WS.
3. Until the WS respond I want to have an animated progress Icon. The classic windows hourglass as an example.
4. If the WS succeed or the answer is an OK I want to change the hourglass by the check icon that is currently being used in the library.
5. Finally, if the WS fails I want to change the hourglass by an X mark.

**Comment by cortinico** [comment]
Hey @rsansores 

Would you be fine if I just expose the `animated_check_icon` attribute so you can replace it with your drawable/animated vector drawable?

> Here is what I'm trying to achieve.

That's definitely cool and would love to get a full request if you plan to do something. I might implement it in the following months but I still have to think if this will be a separated library or a special behavior of this library.

**Comment by rsansores** [comment]
Yes of course. I will make a pull request so you can decide whether to integrate it to the core component.

Regards!

**Comment by cortinico** [comment]
So do you still need me to expose `animated_check_icon`?

**Comment by jbaris** [comment]
I need this feature too.

**Comment by kenshin171** [comment]
has this feature been added?

**Comment by cortinico** [comment]
> has this feature been added?

Not yet. I'm reopening and will start working on this in the near future.
Ideally will go in 0.8.0 (the upcoming release).

**Comment by agforte** [comment]
I am interested in this feature as well. Thanks!

**Comment by etman55** [comment]
Hi @cortinico i need this feature too

**Comment by cortinico** [comment]
> Hi @cortinico i need this feature too

> I am interested in this feature as well. Thanks! Similar to what it is done in this library:
> [shadowfaxtech/proSwipeButton](https://github.com/shadowfaxtech/proSwipeButton)

Hi all 👋 

I'm happy to review a PR or support the development of this functionality. 

I currently can't develop it by myself (at least not in the immediate future) since I'm pretty full. If there are first-time contributors or volunteers that want to pick this up, don't be shy 💪

**Comment by etman55** [comment]
Hi @cortinico 
i have pulled a request for this issue i hope you can take a loot at it 
https://github.com/cortinico/slidetoact/pull/124

**Comment by cortinico** [comment]
> i have pulled a request for this issue i hope you can take a look at it

Awesome, I'll check it out next week 👍
