### ISSUE TITLE
Error Inflating class com.ncorti.slidetoact.SlideToActView

### ISSUE THREAD

**Issue by benevolent13** [cortinico/slidetoact#19]
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [ ] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

In case of bug report, please don't forget to include also:
* Library Version.
* Android Version.
* Emulator/Device specs.
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.

**Comment by cortinico** [comment]
@benevolent13 Can you please fill out the Issue template?
I can't really do anything if you fill in only the title.

**Comment by enylrad** [comment]
Hi, I have had the same problem.

I downloaded the project to see if I found the error. In my case the error was produced because in the librery there is an asset called "ic_check" and in my project too.

I have renamed the asset by another name solving the problem. I would add a prefix to the assets to avoid this kind of problems.

I hope it helps, greetings.

**Comment by squeeish** [comment]
@benevolent13 did you use SlideToActView in a fragment?

**Comment by cortinico** [comment]
@enylrad Thanks for the hint. I'll be prefixing library resources with `slidetoact_` in the next release so there won't be clashes in the future versions of the library.
