### ISSUE TITLE
setOnClickListener not working

### ISSUE THREAD

**Issue by subrud** [cortinico/slidetoact#25]
```java
final SlideToActView confirm_order = findViewById(R.id.confirm_order);

confirm_order.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View v) { 
                 Log.d(TAG, "onClick: v " + v);
                 Toast.makeText(mContext, "Please Swipe", Toast.LENGTH_LONG).show();
             }
         });
```

**Comment by cortinico** [comment]
Hey @subrud 

Yeah you're right and that's actually the intended behavior.
I have one question: Are you trying to intercept **only failed swipes**.

Because I'm afraid the `View.OnClickListener` will be triggered for every click (also for the one the user does when starting to swipe).
Can you please clarify your use case?

**Comment by subrud** [comment]
Actually, when a couple of users were given the app for testing, their initial response was tapping instead of swiping. So I just want to display a toast message of swiping when a user taps on it.

**Comment by cortinico** [comment]
Hey @subrud I'm fixing this here #29 plus I also add another listener to better understand if the user failed to interact with the widget
