### ISSUE TITLE
Slide from right to left

### ISSUE THREAD

**Issue by gyorfiavarlehel** [cortinico/slidetoact#3]
Hi,

This is an awesome library! Thank you!

Is it possible to update the slider to remain active after you switched it on?
I would like to use it to start and stop an app.

It would be awesome if you can update it to work in the following way:
1. Slide from left to right to activate the slider.
2. After the Done animation the slider should appear again but in this case with an <- arrow.
3. Slide from right to left to deactivate the slider.
4. After the Done animation the slider should appear again with an -> arrow.

Thanks.

**Comment by cortinico** [comment]
Hey @gyorfiavarlehel 

Thanks for your suggestion.
Unfortunately, I don't think I'm going to do this soon since it will increase the complexity of the mathematics for the animation. Furthermore, is just to address an edge use case.

On the other hand, I'd love to suggest you to try using two sliders and rotating them.
You can simply rotate the second with: `android:rotation="180"`
Then you just need to rotate the tick or the text (if you use them), and you should be set.

Let me know if you need some sample code.
Best ;)

**Comment by adrienrx** [comment]
Hey @cortinico , 

How do you rotate the text?

**Comment by cortinico** [comment]
> How do you rotate the text?

Hey @adrienrx Can you be more specific? (or open a new issue eventually)?

**Comment by adrienrx** [comment]
Hey @cortinico, 
![reversed text](https://i.ibb.co/k8LndMg/Screenshot-2019-03-28-at-17-21-58.png)

I would like to rotate the reject text. I've rotated the slider. But I can't find a way to rotate the text. I tried textAppearance / findViewById (but no id) / findViewByTag (but no tag) / browsing the view group (failed as well).

> Then you just need to rotate the tick or the text (if you use them), and you should be set.

How do you rotate the text? 

Many thanks
